# Development image, source is mounted via volume

FROM python:3.8
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="Jammer back-end" \
    org.label-schema.description="Docker image for seed of Jammer's backend" \
    org.label-schema.url="https://github.com/akseiya/jammer-backend" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/akseiya/jammer-backend" \
    org.label-schema.vendor="Wonsze" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"
LABEL maintainer="Wonsze"

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
ENV devenv yes

# Gunicorn start in current directory, so app/app is app.app.
# It also expects WSGI callable to be named `application` by default.
# --max-requests - Shotgun
CMD ["gunicorn",                               \
     "--log-level=debug",                      \
     "--bind=0.0.0.0:5000",                    \
     "--max-requests=1",                       \
     "app.app:app"]
